[2022-11-12T13:12:15.395+0000] {taskinstance.py:1165} INFO - Dependencies all met for <TaskInstance: load_to_dwh_v2.extract_and_clean_data manual__2022-11-12T13:12:14.264852+00:00 [queued]>
[2022-11-12T13:12:15.412+0000] {taskinstance.py:1165} INFO - Dependencies all met for <TaskInstance: load_to_dwh_v2.extract_and_clean_data manual__2022-11-12T13:12:14.264852+00:00 [queued]>
[2022-11-12T13:12:15.412+0000] {taskinstance.py:1362} INFO - 
--------------------------------------------------------------------------------
[2022-11-12T13:12:15.412+0000] {taskinstance.py:1363} INFO - Starting attempt 1 of 6
[2022-11-12T13:12:15.413+0000] {taskinstance.py:1364} INFO - 
--------------------------------------------------------------------------------
[2022-11-12T13:12:15.434+0000] {taskinstance.py:1383} INFO - Executing <Task(PythonOperator): extract_and_clean_data> on 2022-11-12 13:12:14.264852+00:00
[2022-11-12T13:12:15.440+0000] {standard_task_runner.py:54} INFO - Started process 180 to run task
[2022-11-12T13:12:15.444+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'load_to_dwh_v2', 'extract_and_clean_data', 'manual__2022-11-12T13:12:14.264852+00:00', '--job-id', '254', '--raw', '--subdir', 'DAGS_FOLDER/postgre_create_table.py', '--cfg-path', '/tmp/tmpr2g8htin']
[2022-11-12T13:12:15.445+0000] {standard_task_runner.py:83} INFO - Job 254: Subtask extract_and_clean_data
[2022-11-12T13:12:15.446+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/***/dags/postgre_create_table.py
[2022-11-12T13:12:16.038+0000] {task_command.py:384} INFO - Running <TaskInstance: load_to_dwh_v2.extract_and_clean_data manual__2022-11-12T13:12:14.264852+00:00 [running]> on host f7644c80e7bb
[2022-11-12T13:12:16.183+0000] {taskinstance.py:1592} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=nahom
AIRFLOW_CTX_DAG_ID=load_to_dwh_v2
AIRFLOW_CTX_TASK_ID=extract_and_clean_data
AIRFLOW_CTX_EXECUTION_DATE=2022-11-12T13:12:14.264852+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2022-11-12T13:12:14.264852+00:00
[2022-11-12T13:12:16.185+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.7/site-packages/pandas/util/_decorators.py:311: ParserWarning: Falling back to the 'python' engine because the 'c' engine does not support regex separators (separators > 1 char and different from '\s+' are interpreted as regex); you can avoid this warning by specifying engine='python'.
  return func(*args, **kwargs)

[2022-11-12T13:12:24.594+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.7/site-packages/pandas/io/parsers/readers.py:586: ParserWarning: Length of header or names does not match length of data. This leads to a loss of data with index_col=False.
  return _read(filepath_or_buffer, kwds)

[2022-11-12T13:12:26.330+0000] {logging_mixin.py:117} INFO - data loaded successfully!!!
[2022-11-12T13:12:26.370+0000] {python.py:177} INFO - Done. Returned value was: None
[2022-11-12T13:12:26.390+0000] {taskinstance.py:1406} INFO - Marking task as SUCCESS. dag_id=load_to_dwh_v2, task_id=extract_and_clean_data, execution_date=20221112T131214, start_date=20221112T131215, end_date=20221112T131226
[2022-11-12T13:12:26.481+0000] {local_task_job.py:164} INFO - Task exited with return code 0
[2022-11-12T13:12:26.512+0000] {local_task_job.py:273} INFO - 1 downstream tasks scheduled from follow-on schedule check
